### ISSUE TITLE
v2.45 cannot be closed if there is an error

### ISSUE THREAD

**Issue by drexjj** [SigmazGFX/freedv_ptt#1]
v2.45 cannot be closed if there is an error or unmet dependency. Pressing the OK button or the X button keeps cycling the same error. The process has to be killed manually.

**Comment by SigmazGFX** [comment]
Added pkill assertion to the gtk dialog callback close function for the device detection error box. 
This should terminate the process if the user doesn't wish to, or cannot connect a USB audio device and would like to terminate the application.

**Comment by drexjj** [comment]
Works like a charm now. Thanks.
